version: '3.8'

services:
  geth:
    image: ghcr.io/denislav-mladenov/go-ethereum:latest
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    command: 
      --dev
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.corsdomain "*"
      --http.api personal,db,eth,net,web3
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.origins "*"
      --ws.api personal,db,eth,net,web3
