name: docker-build

on:
  pull_request:
    branches: [ "master" ]
    types: [ labeled ]

  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: denislav-mladenov/go-ethereum

jobs:
  build-and-push:
    if: ${{ github.event.label.name == 'CI:Build' }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
    - uses: actions/checkout@v4

    - name: Login to registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build docker image
      uses: docker/build-push-action@v5
      with: 
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
